### ISSUE TITLE
Project Build Error

### ISSUE THREAD

**Issue by Mark-Onopchenko** [christianGRogers/TAAM#5]
I cloned the project as is from GitHub and opened it with Android Studio.
However, when I tried to build it, I got the following error:
<img width="1287" alt="image" src="https://github.com/christianGRogers/TAAM/assets/169728182/fb65e72d-e577-4d24-bf7c-a685716a62cd">

**Transcribed error text:**
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. 
  The Google Services Plugin cannot function without it. 
  Searched locations: /Users/onopchenkomark/Code/CSCB07/TAAM/TAAMCollectionManager/app/src/debug/google-services.json, /Users/onopchenkomark/Code/CSCB07/TAAM/TAAMCollectionManager/app/src/debug/google-services.json, /Users/onopchenkomark/Code/CSCB07/TAAM/TAAMCollectionManager/app/src/google-services.json, /Users/onopchenkomark/Code/CSCB07/TAAM/TAAMCollectionManager/app/src/debug/google-services.json, /Users/onopchenkomark/Code/CSCB07/TAAM/TAAMCollectionManager/app/src/Debug/google-services.json, /Users/onopchenkomark/Code/CSCB07/TAAM/TAAMCollectionManager/app/google-services.json

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 11s
39 actionable tasks: 39 executed

**Comment by neloduka-sobe** [comment]
https://stackoverflow.com/questions/33866061/error-file-google-services-json-is-missing-from-module-root-folder-the-google

Had the same issue, solved for me.
Close issue if fixed
